### ISSUE TITLE
How do you add className - need to update doc

### ISSUE THREAD

**Issue by Multi-Thinker** [binodswain/react-faq-component#28]
Trying to add className by reading the recent PR, can't figure out how. would be good if document can state how. :) 

Thanks for the great lib

**Comment by binodswain** [comment]
In the current package, you cannot add any class name to row or content div.

you can use "faq-row-wrapper","faq-title", "faq-body", "faq-row", "row-content-text", "row-content" and "row-title" class names to apply the styles to respective elements.

```scss
.faq-row-wrapper{
    .faq-title{
    }

    .faq-body{
        .faq-row{
            .row-title{
            }

            .row-content{
                .row-content-text{
                }
            }
        }
    }
}
```
you can test it on the demo website.

**Comment by binodswain** [comment]
updated readme. 10a02881167d94f1c39826afac604b96fea429a7
