### ISSUE TITLE
How to remove thick border when clicked an faq item ?

### ISSUE THREAD

**Issue by leanesanity** [binodswain/react-faq-component#36]
![image](https://user-images.githubusercontent.com/39898232/96695511-51acf180-13bc-11eb-8035-f9e9f871f73a.png)

Hello Good Day,

I want to use this library for my project. 
Can you help me with how to remove the border when I clicked an faq item ?

Many thanks and always keep safe :)

**Comment by binodswain** [comment]
All the row titles are focusable, so the user can navigate through the faq list using tabs and expand those using the return/enter or space button.

 I have made it optional to enable this feature in the component. By default, it will be disabled and you need to pass a prop in the config to enable this feature.

The change is reflecting on the demo website. Follow the usage mentioned in the readme.

**Comment by leanesanity** [comment]
Oh, Thank you for that answer. Now I notice it.
