### ISSUE TITLE
can we use some icon instead of 'V' text

### ISSUE THREAD

**Issue by rajashekar-ayla** [binodswain/react-faq-component#54]
trying to use icon
`config={{
            arrowIcon: {DownChevron}
          }}
`

**Comment by binodswain** [comment]
Try this way.
```jsx
<Faq data={data}
    config={{
       arrowIcon: <DownChevron/>
    }}
/>
```
https://codesandbox.io/s/nostalgic-cherry-ck2dp?file=/src/App.js
