### ISSUE TITLE
I need get the event click of the title

### ISSUE THREAD

**Issue by jcyber2017** [binodswain/react-faq-component#55]
I need expand one youtube video after expanding the FAQ. but I can't get the event that trigger the expanding process. There is one way?

**Comment by binodswain** [comment]
Can you share sample implementation in https://codesandbox.io/.

**Comment by jcyber2017** [comment]
I already found a way, I separated each item in one different FAQ, and added onClick Event to that div and used iframe.requestFullScreen()
