### ISSUE TITLE
Use +/- arrow icon instead of V icon

### ISSUE THREAD

**Issue by jsdude0220** [binodswain/react-faq-component#62]
I think the arrow icon is available with only 1 type and just rotate it when click row.
Can we use +/- style icon, so show - icon when collapse and show + icon when expand.

**Comment by binodswain** [comment]
update the package to latest version and pass `expandIcon` and `collapseIcon` in config props.
```
const config = {
    animate: true,
    expandIcon: "+",
    collapseIcon: "-",
};
```

**Comment by jsdude0220** [comment]
Thanks. @binodswain 👍

**Comment by 0xCardiE** [comment]
How about if we could use image instead of letters?
