### ISSUE TITLE
Error while building gatsby app

### ISSUE THREAD

**Issue by vzkiss** [binodswain/react-faq-component#9]
Received the following error while building gatsby application.

> Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=1  30&args[]=object&args[]= for the full message or use the non-minified dev environment for full   errors and additional helpful warnings.

No issues in gatsby develop mode.

**Comment by binodswain** [comment]
react-faq-component@1.0.4

**Comment by vzkiss** [comment]
The issue persist.

**Comment by binodswain** [comment]
@vzkiss I tried creating a new gatsby site and added `react-faq-component@1.0.4`
I am able to create the production build. Here is the demo site
https://github.com/binodswain/react-faq-gatsby-demo

**Comment by vzkiss** [comment]
I checked and the window object is indeed removed. It's the 1.0.4 version
I heard using the document object can create the same error message.

When the Faq component is used the build process still throws the error with v1.0.4
<img width="685" alt="Screenshot 2020-03-11 at 22 06 38" src="https://user-images.githubusercontent.com/22350628/76464183-25240680-63e5-11ea-83fc-6422c7efa3e7.png">

**Comment by binodswain** [comment]
Can you create a repo with your faq changes, so I can reproduce the same error and take a look at it.
